"""add tracker_event table

Revision ID: e96d18523078
Revises: 94a78751b9ba
Create Date: 2026-10-04 19:24:57.840714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96d18523078'
down_revision: Union[str, Sequence[str], None] = '94a78751b9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_event_user_id'), 'tracker_event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_event_user_id'), table_name='tracker_event')
    op.drop_table('tracker_event')
    # ### end Alembic commands ###
